### ISSUE TITLE
a:5:{i:0;s:107:"SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'shipping_method' in where clause is ambiguous";i:1;s:6545:"#0

### ISSUE THREAD

**Issue by mvgucht** [DPDBeNeLux/magento-DPD_Shipping#1]
System:
- Magento: 1.9.0.1

Installed via magento-connect

**Comment by hostep** [comment]
Hi Michiel

Can this get merged into the master branch?
We also ran into this problem. And your fix fixed it for us.

Thanks!
