### ISSUE TITLE
unable to generate retourlabels DPD-Magento Plug-in

### ISSUE THREAD

**Issue by Daprey** [DPDBeNeLux/magento-DPD_Shipping#16]
Hi,
in our shop we wan't to generate a retour label, but when we try we are getting the message: Only non-interlaced images are currently supported.. I've already adjust the image to non interlaced, but i still get this message. Ideas anyone? Perhaps another check where to adjust the image... did it under sells now.

Thanks in advance! Sincerely Daphne

**Comment by mvgucht** [comment]
This error comes from your logo beeing embedded in a pdf letter with instructions on how to drop off the parcel in the shop. The only way to get this to work (without changing the extension) is by saving your website logo as deinterlaced (in for example paint) and uploading it again.

The only thing that would change by doing so is that your logo won't be shown blurry while downloading and will only appear when fully downloaded. (only affects slow internet connections)
