### ISSUE TITLE
alternative adress not on label

### ISSUE THREAD

**Issue by Daprey** [DPDBeNeLux/magento-DPD_Shipping#17]
Hi,  if our customers pick an alternative adress for delivery than they have chosen for invoice, the adress of invoice is on the dpd label, as a delivery adress. How to fix this?

Thanks, greetings Daphne

**Comment by mvgucht** [comment]
Reproduction steps:

1. Enter different billing and shipping address
2. select a Parcelshop
3. select home delivery
4. place order

=> parcelshop is still selected ...

**Comment by mvgucht** [comment]
After a whole day of research i finaly found a solution. 
the observer.php saves the parcelshop address over the shipping address when the cnee clicks on the continue button. 
Solution is to use the checkou_submit_all_after for all checkouts, one page or one step. This ensures that the address is only overwritten after the submit order is clicked.

I'll try to clean up and test my code tomorrow and i will post it as a branch when i'm done.

**Comment by Daprey** [comment]
Hi Mvgucht, is this something i can adjust in the magento environment? And if so, where to adjust? The way i read the given solution is that dpd should take action. Kind regards Daphne

**Comment by Daprey** [comment]
Any updates regarding this post yet? The functionality still doesn't work properly, will be great to hear from you, Kind regards Daphne

**Comment by mvgucht** [comment]
I've uploaded my temp solution: https://github.com/DPDBeNeLux/magento-DPD_Shipping/tree/fix-issue%2317

this should work on al magento versions, i tested it with 1.6, 1.8, 1.9 on Wamp and CentOS.

!!!BUT!!! i still need to clean it up. it works but doesn't look nice (the code )
