### ISSUE TITLE
Add option to choose to calculate to 'NCP' / 'NP' or choose 1 standard

### ISSUE THREAD

**Issue by emilev79** [DPDBeNeLux/magento-DPD_Shipping#19]
We only ship 'NP' because we have this agreement on shipping with DPD.
With the current extension it standard calculates on weight so we can't use it 'out of the box'

**Comment by emilev79** [comment]
I meant SCP / NCP by the way.. But would be really great to have them all 4 off course

**Comment by mvgucht** [comment]
Hey emilev79,

for the magento back-end label printing this isn't an option, the weight and measurements are becoming mandatory for a lot of our services, so the web service uses this to calculate the correct service code.
A practical solution in this case is that your sales person sets the price for both NP and SP the same.

As for DelisPrint, you could use a DelisPrint rule to change every SP (or SCP) to NP (or NCP). 
Your local depot IT guy is best placed to help you with this. My DelisPrint knowledge is basic :)

**Comment by emilev79** [comment]
Hi Michiel, as we export to delisprint we now changed the Dpdgrid.php
Replaced all SCP to NCP in the code. I know that is a very rude solution but it gets the job done..
