### ISSUE TITLE
Translation front end labels

### ISSUE THREAD

**Issue by emilev79** [DPDBeNeLux/magento-DPD_Shipping#20]
Hi,

Not an issue but it would be really nice of we could use inline translation for the frontend labels. See image attached. Otherwise please let me know where to change the title in the code. 

![translation](https://cloud.githubusercontent.com/assets/9929020/6417580/8ab204a2-beae-11e4-81f6-b3ac1fe9fa8d.jpg)

**Comment by martinhelfert** [comment]
You can change the title here: System Configuration > Sales > Shipping Methods. There's a "Shipping Method Name" for each method:

![configuration___system___magento_admin](https://cloud.githubusercontent.com/assets/3244021/6869472/ae4a28bc-d494-11e4-9e27-ac7df20eaaa7.jpg)

**Comment by mvgucht** [comment]
And I guess you can add a name for every one of your store views.
