### ISSUE TITLE
Product weight always 0.00 on DPD (PDF) Labels

### ISSUE THREAD

**Issue by onepack** [DPDBeNeLux/magento-DPD_Shipping#21]
I have installed this module for two DPD customers with the printing to PDF option.
Today I got a call from one customer that they got fined by DPD as they seemed to send Small Packages as they really were sending quite heavy stuff.
Next they told me they should have at least two stickers when they have a shipping weigh of 30kg and more but only one label would be available.
I went to check myself and was amazed that on all the PDF Shipping labels that I downloaded the weight was 0.00.
So I checked the other customer and there I saw the same thing. The DPD label would show a weight of 0.00 for a product that had a weight entered in the product detail page.

**Comment by mvgucht** [comment]
Hey onepack,

about the weight, in the Netherlands there are a couple of depots that use 'meten en wegen' system that automatically fines when a declared weight is under the actual weight. 

**two stickers** can be made when you **create two (or more) shipments** (selecting dpd home or parcelshop) entering a **fake track and trace number** for both and then running **'generate label and complete'** action in the dpd order view.

As for the last remark, when a weight is set in the product it should be displayed on the label also. (Given that the weight is above 10 grams)
What version of the extension are you using?

**Comment by onepack** [comment]
Hi MvGucht,

This was about DPD sending a fine to the customer.
They used to have Delisprint but use the module now with the DPD webservice.
It saves them a lot of time regarding the sending process but they are now not to happy about the fines. ;-)
They actually never have a small package because of the size of the products but there is no option to cancel SP in the backend (unless I hack the module).
I asked my customer to contact DPD so the SP option can be "denied" on the DPD side but the DPD lady there told my customer that was not possible.
So I probably end up hacking the module to disable the small package from there.

As for the weight that is always 0.0000
For this customer I use the latest version 1.1.1 together with the Print to PDF "extension".

**Comment by mvgucht** [comment]
Hey onepack,

I got that DPD is sending fines, it is an automated system to ensure correct data. And i'm sorry about the inconvenience. 

I propose that (for now) you 'hack' this file (locally) https://github.com/DPDBeNeLux/magento-DPD_Shipping/blob/master/app/code/community/DPD/Shipping/Model/Webservice.php
on line 456 set a default weight of 30 kg. (3000 decagrams)

```php
454                 'parcels' => array( 
455                     'customerReferenceNumber1' => $shipment->getIncrementId(), 
456                     'weight' => 3000 //round($weight,0) 
457                 ), 
 ```

we are working on the next version of the extension and i'll add a 'default weight' configuration to the list.
