### ISSUE TITLE
Design of 'choose a parcelshop' 

### ISSUE THREAD

**Issue by emilev79** [DPDBeNeLux/magento-DPD_Shipping#22]
We have gotten several phonecalls from customers who did not manage to place their order. It turned out they choose 'parcelshop'. For them it is not clear they need to select the parcelshop.

**Comment by mvgucht** [comment]
Hey Emilev79

Normally you can’t get to the next step or confirm the order without selecting a shop, and an error message should show.

Met vriendelijke groeten / Sincères salutations / Best regards,
Michiel Van Gucht
DPD IT Integration Specialist Benelux Pickup | ParcelShop
T. +3215501572 | M. +32474502717
DPD (Belgium) NV

**Comment by emilev79** [comment]
That would do with the 'standard' checkout. But when you use a 'one page' checkout and choose a 'overlay' the customer could easily skip it. Please see images attached.
What would solve this is the automatic 'pop up' of the overlay. 
 

It would be really great if the '
![overlay](https://cloud.githubusercontent.com/assets/9929020/7409110/ec18564c-ef23-11e4-9c19-b5b5c60882f9.jpg)
![parcelshops](https://cloud.githubusercontent.com/assets/9929020/7409111/edfc6e4e-ef23-11e4-9a9a-9423c5f14c71.png)

**Comment by mvgucht** [comment]
I would add some javascript (jquery) to the one page template that when that radio box is selected the link is 'clicked'.
