### ISSUE TITLE
Three shipment labels for one product in shipment needed

### ISSUE THREAD

**Issue by onepack** [DPDBeNeLux/magento-DPD_Shipping#23]
A client called me that they have quite often customers that buy a big family tent that is quite heavy,
It has a bag with heavy tent poles, a bag with the inner tent and a bag with the outer tent.
They like to have three shipping labels, for each bag one although it is one product for a customer when checking out.
I see no option to achieve this with the current module.
Do you have any suggestion?

**Comment by mvgucht** [comment]
Hey onepack,
these parcels are defined as 1 product in your magento I presume?

**Comment by onepack** [comment]
Hi Mvgucht,
Yes correct. I just updated the case to make that more clear but you were too fast :-)

**Comment by mvgucht** [comment]
The only thing I can think of is to remove the check for shipments, and in doing so forcing the module to generate labels for orders that already have a shipment linked to it.
