### ISSUE TITLE
Can't print label for parcelshop because name is too long

### ISSUE THREAD

**Issue by martinhelfert** [DPDBeNeLux/magento-DPD_Shipping#25]
A customer has chosen to deliver to a parcelshop. Printing the label fails with this message:

```
2015-05-20T12:06:42+00:00 ERR (3): Webservice storeOrders failed:
2015-05-20T12:06:42+00:00 ERR (3): stdClass Object
(
    [faultCode] => COMMON_3
    [message] => mpsexpHeader.rname1; Spätkauf Kiosk Gold-Eck - Keine Barzahlung ! > 35
)
```

So it seems that the name can only be 35 chars. But that's the name which is assigned to that parcelshop ID by DPD itself?!

Additionally, I can't change the delivery address afterwards. I had to change the dpd_parcelshop_id which is assigned in sales_flat_order to get the new label.

**Comment by mvgucht** [comment]
Hey Martinhelfert,

yes, this is a know problem, the only thing I can do is forward your notification to my German colleagues and ask if they can limit the name to 35 chars. (I've done this quite some times before now :-( ) 

I'm sorry for the inconvenience and I hope they'll put it right asap.
