### ISSUE TITLE
Can't Print DPD Label - name too long

### ISSUE THREAD

**Issue by onepack** [DPDBeNeLux/magento-DPD_Shipping#28]
Hi there,
It is impossible to print a DPD label.
The corresponding error message:

2015-06-23T08:41:38+00:00 ERR (3): Webservice storeOrders failed:
2015-06-23T08:41:38+00:00 ERR (3): stdClass Object
(
    [faultCode] => COMMON_3
    [message] => generalShipmentData.recipient.street; Eerste Jan van der Heijdenstraat 157 H  > 35
)

Can the 35 limit be altered to something like 45? I assume this will occur more often.

**Comment by mvgucht** [comment]
Hey,

This is not a restriction of Magento, but on the Delicom Web Services. They can’t be changed. You’ll have to alter the address manually to something below 35 chars.

Met vriendelijke groeten / Sincères salutations / Best regards,
Michiel Van Gucht
DPD IT Integration Specialist Benelux Pickup | Pickup
T. +3215501572 | M. +32474502717
DPD (Belgium) NV
