### ISSUE TITLE
Saturday delivery error [You are not enrolled for this service. Please contact your depot.]

### ISSUE THREAD

**Issue by robinero** [DPDBeNeLux/magento-DPD_Shipping#31]
Hey mvgucht,

I'm hoping you can help me out with this issue.

We've added https://github.com/DPDBeNeLux/magento-DPD_Shipping/commit/129a8d0166d7f0d885dfa3d7002ef33f9792a167 to the DPD module.
However when we try to create a label, when Saturday Delivery is enabled, the mass action **Create label and Complete** throws the following error:
> You are not enrolled for this service. Please contact your depot.

Are we doing something wrong?

**Comment by mvgucht** [comment]
Hey robinero,

you aren't doing anything wrong, the Saturday delivery service isn't activated. please email me or customer it directly your delisID (not via github pls :smile:) so we can activate it.

**Comment by robinero** [comment]
Ah! Alright, thanks!
We've contacted DPD and they activated the Saturday delivery service.

Everything's working now.
