### ISSUE TITLE
Question about merging 2 mass actions

### ISSUE THREAD

**Issue by robinero** [DPDBeNeLux/magento-DPD_Shipping#33]
Hey mvgucht,

Back yet again with a question.

Is it possible to merge the mass actions "Generate label and Complete" and "Download all undownloaded"?
And if it is, are there any downsides to it?

Thanks!

Kind regards,
Robin

**Comment by mvgucht** [comment]
Hey Robin,

you could try and add the download action at the end of the generate label action in the controller:

https://github.com/DPDBeNeLux/magento-DPD_Shipping/blob/8216ce0bd1f6358f39dffca40595cd4af4506aaa/app/code/community/DPD/Shipping/controllers/Adminhtml/DpdorderController.php#L161

```php
$this->_redirect('*/*/index');
```
becomes


```php
//$this->_redirect('*/*/index');
dowloadAllUndownloadedAction()
```

should work :)
