### ISSUE TITLE
Undefined variable: returnId  in /DPD/Shipping/controllers/Adminhtml/DpdorderController.php on line 75

### ISSUE THREAD

**Issue by koenner01** [DPDBeNeLux/magento-DPD_Shipping#34]
As the title says, I'm getting undefined variable notice when trying to create a return label through the Magento backend by clicking the 'DPD Return Label' button on the sales_order/view page

**Comment by koenner01** [comment]
After fixing this, a new undefined variable notice pops up
```php
Notice: Undefined variable: parcelshop in /DPD/Shipping/Model/Returnlabels.php on line 36
```

**Comment by mvgucht** [comment]
change that line to 

```php
if (isset($parcelshop)) {
```
Are you using CentOS by any chance?
