### ISSUE TITLE
provide modeman and composer.json

### ISSUE THREAD

**Issue by Webmasterei** [DPDBeNeLux/magento-DPD_Shipping#44]
this would be superawesome for easy upgrades.

**Comment by mvgucht** [comment]
https://github.com/DPDBeNeLux/magento-DPD_Shipping/pull/27
https://github.com/DPDBeNeLux/magento-DPD_Shipping/pull/18

Seen that I don't use a setup like that, and I'm working on a new extension this will not be officially supported ad this time.
