### ISSUE TITLE
Can't print labels and complete

### ISSUE THREAD

**Issue by Webmasterei** [DPDBeNeLux/magento-DPD_Shipping#46]
I installed the extension but it is not possible to print labels.
Extension konfiguration:
![auswahl_096](https://cloud.githubusercontent.com/assets/6458728/11451630/13616d92-95cd-11e5-80c8-c2bbcdccdc1e.png)
An here's the different errors:
![auswahl_095](https://cloud.githubusercontent.com/assets/6458728/11451635/1f389b36-95cd-11e5-89f2-2cf6b771fb2e.png)
Thanks for helping out here.

**Comment by mvgucht** [comment]
Hey,

you need to contact your local depot and ask for a delicom web service activation for magento.
this service is not active by default.

**Comment by Webmasterei** [comment]
Hi, 
the mydpdbusiness portal says "MyDPD Business Webservice" isn't that the right one?

**Comment by mvgucht** [comment]
I don't think so. 
you'll have to contact the local depot, because they can send  you the other settings (address) too.
The address is needed to generate the lable, but it has to correspond exactly to what we have in our database. (and I can only access Benelux customers)

**Comment by Webmasterei** [comment]
Still not getting an answer from the DPD locals.... 

I tried now with putting https://public-wsstage.dpd.com/services/ into the URL field. 
Also the error above comes really really fast. So fast that I guess that it stops processing even before the login process.

Can you confirm:
A) That this "https://public-wsstage.dpd.com/services/" is the right url, including the trailing slash?
B) I can take addrress data from the mydpdbusiness portal as it's printed there.
C) That the Address Code for Germany is "DE"

**Comment by mvgucht** [comment]
Hey,

to answer you questions:
A) The url for stage is: https://public-ws-stage.dpd.com/services/
B) Yes, BUT, the web service account has to be activated by delicom/local depot.
C) Yes, Country code is DE.
