### ISSUE TITLE
Improve the UX of the parcelshop picking widget

### ISSUE THREAD

**Issue by hostep** [DPDBeNeLux/magento-DPD_Shipping#50]
Hi

The UX of the parcelshop picking widget needs some attention I think.

See:
![screen shot 2016-02-22 at 12 34 26](https://cloud.githubusercontent.com/assets/85479/13217161/cd2d2622-d960-11e5-8878-c644f3a631d1.png)

When trying to select a pickup point, I was clicking the DPD logo's on the map, or the name of the pickup point in the right sidebar, and nothing really happened. So I assumed it was selected, and used the close button on the top right corner (which to me seemed really strange) and tried to proceed in the checkout, but got an error saying I should select a shipping method.

After about 20 minutes (I already started debugging the javascript to see if something went wrong there), my eye suddenly noticed that `Ship to this pickup point` link, which was actually selecting the pickup point.

I let a colleague of mine test this without telling her anything, and she made the exact same mistake as myself, so I'm not the only one having this problem, and probably other people will also be very confused about this.

Maybe someone can take a look at turning this into a more intuitive way of working, because right now, it's not really clear enough how you select a certain pickup point.

(the same problem happens when you use inline maps instead of the overlay, it is even more confusing without the overlay I think)

**Comment by mvgucht** [comment]
Hey,

normally if you click a shop name you get the bubble above the selected shop:

![001](https://cloud.githubusercontent.com/assets/8297140/13217513/4f1482b4-d963-11e5-8862-cbc2dd459eff.png)

But I agree, the 'shop to this shop' link should be at least highlighted when onmouseover. 
I think it is linked to the link css of the shop too, but for that I need to do more testing.

**Comment by hostep** [comment]
Ah ok, I don't get that bubble, only the arrow pointing down, but nothing else, so I actually have to do some extra debugging then. I'll get back to you :)

See:
![screen shot 2016-02-22 at 13 29 49](https://cloud.githubusercontent.com/assets/85479/13218230/645081dc-d968-11e5-898f-04959f3a3d41.png)

**Comment by mvgucht** [comment]
I thought I merged a solution to the master. 

check issue 32:

https://github.com/DPDBeNeLux/magento-DPD_Shipping/issues/32

**Comment by hostep** [comment]
Aha indeed, you are correct.
Only issue is a horizontal scrollbar right now.

![screen shot 2016-02-22 at 13 34 16](https://cloud.githubusercontent.com/assets/85479/13218330/0f356a54-d969-11e5-9bd1-3fc2722886dd.png)

But we can live with that for now.
I'll close this ticket, because after this fix, the UX actually makes sense.

Thanks Michiel.

**Comment by mvgucht** [comment]
configure the width of the locator a bit bigger in the shipping method settings. horizontal scrollbar will disappear.

**Comment by hostep** [comment]
Correcto, changing the default 600 to 610 fixes the issue, thanks once again! :)
